spring:
  application:
    name: stock-market-chart-admin

server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/