spring:
  application:
    name: eureka-client-service-security

server:
  port: 6001
  servlet:
    context-path: /security

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

jwt:
  secret: ibmfullstack

secure:
  ignored:
    urls:
      - http://localhost:9000/ibm/user/signin
      - http://localhost:9000/ibm/user/signup
      - http://localhost:9000/ibm/security/authenticate
      - http://localhost:6001/security/authenticate