spring:
  application:
    name: eureka-client-service-security

server:
  port: 9001
  servlet:
    context-path: /security

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

jwt:
  secret: ibmfullstack